// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB654YtVmq10URAgNnwZb2wV9tDReEcmOE',
    appId: '1:433142132028:web:7d44f77f1d62cfe6190239',
    messagingSenderId: '433142132028',
    projectId: 'galini-d1a1a',
    authDomain: 'galini-d1a1a.firebaseapp.com',
    storageBucket: 'galini-d1a1a.appspot.com',
    measurementId: 'G-7L6KY6LXY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq0JBDD0MMGAx0YeoKCOY76mykcgTqG8E',
    appId: '1:433142132028:android:e9bdfbc9db22d29f190239',
    messagingSenderId: '433142132028',
    projectId: 'galini-d1a1a',
    storageBucket: 'galini-d1a1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsWvaX-ChAe9aeciq_UX-Q97ug7UTVu9E',
    appId: '1:433142132028:ios:4f25cc0d3702d136190239',
    messagingSenderId: '433142132028',
    projectId: 'galini-d1a1a',
    storageBucket: 'galini-d1a1a.appspot.com',
    iosBundleId: 'com.example.healthcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsWvaX-ChAe9aeciq_UX-Q97ug7UTVu9E',
    appId: '1:433142132028:ios:4f25cc0d3702d136190239',
    messagingSenderId: '433142132028',
    projectId: 'galini-d1a1a',
    storageBucket: 'galini-d1a1a.appspot.com',
    iosBundleId: 'com.example.healthcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB654YtVmq10URAgNnwZb2wV9tDReEcmOE',
    appId: '1:433142132028:web:bf00f77c80c894ec190239',
    messagingSenderId: '433142132028',
    projectId: 'galini-d1a1a',
    authDomain: 'galini-d1a1a.firebaseapp.com',
    storageBucket: 'galini-d1a1a.appspot.com',
    measurementId: 'G-95W6DSN53Q',
  );

}